name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: project-8bf7325f-4fa0-465b-953
  REGION: asia-south1
  SERVICE: ml-api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions-sa@project-8bf7325f-4fa0-465b-953.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and Push Image
        run: |
          gcloud builds submit --tag gcr.io/$PROJECT_ID/ml-api

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE \
            --image gcr.io/$PROJECT_ID/ml-api \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated